###
# 작성 전 로그인
POST http://localhost:3000/login
Content-Type: application/json

{
  "no": "20210010001",
  "password": "asdf1234"
}

###
# 비리 정보 작성
POST http://localhost:3001/v1/corruption-report
x-access-token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDUxNjM0MTI2OTU2NDVhNjAwNGVmYzAiLCJyb2xlcyI6WyJzdHVkZW50Il0sInBlcm1pc3Npb25zIjpbXSwiaW5mbyI6IjYwNTE2MzQxMjY5NTY0NWE2MDA0ZWZjMSIsImlhdCI6MTYxNTk2NTAyOCwiZXhwIjoxNjE1OTY1NjI4LCJhdWQiOiJodHRwczovL3N3N3VwLmNibnUuYWMua3IiLCJpc3MiOiLstqnrtoHrjIDtlZnqtZAgU1fspJHsi6zrjIDtlZnsgqzsl4Xri6giLCJzdWIiOiJrbWFobkBjYm51LmFjLmtyIn0.JnWMBs8pNOE41FrgcrcSu5adI8vFDyARXTPeYn0UfUcLzTSIdlz4XxbKA35RRJ6AHGf66xOwI55bqwSiLM_UcA
Content-Type: application/json

{
  "title": "테스트",
  "content": "<h1>테스트</h1><p>테스트입니다.</p>"
}

###
# 비리 정보 가져오기
GET http://localhost:3001/v1/corruption-report
x-Access-Token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDUxNjM0MTI2OTU2NDVhNjAwNGVmYzAiLCJyb2xlcyI6WyJzdHVkZW50Il0sInBlcm1pc3Npb25zIjpbXSwiaW5mbyI6IjYwNTE2MzQxMjY5NTY0NWE2MDA0ZWZjMSIsImlhdCI6MTYxNTk2NTAyOCwiZXhwIjoxNjE1OTY1NjI4LCJhdWQiOiJodHRwczovL3N3N3VwLmNibnUuYWMua3IiLCJpc3MiOiLstqnrtoHrjIDtlZnqtZAgU1fspJHsi6zrjIDtlZnsgqzsl4Xri6giLCJzdWIiOiJrbWFobkBjYm51LmFjLmtyIn0.JnWMBs8pNOE41FrgcrcSu5adI8vFDyARXTPeYn0UfUcLzTSIdlz4XxbKA35RRJ6AHGf66xOwI55bqwSiLM_UcA

###
# 다른 아이디로 로그인
POST http://localhost:3000/login
Content-Type: application/json

{
  "no": "20200010001",
  "password": "asdf"
}

###
# 비리 정보 가져오기(다른 사용자)
GET http://localhost:3001/v1/corruption-report
x-Access-Token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDUxNjk1YzIxYWVlODM3OTQ5OGMxYzUiLCJyb2xlcyI6WyJzdHVkZW50Il0sInBlcm1pc3Npb25zIjpbXSwiaW5mbyI6IjYwNTE2OTVkMjFhZWU4Mzc5NDk4YzFjNiIsImlhdCI6MTYxNTk2NTYwOSwiZXhwIjoxNjE1OTY2MjA5LCJhdWQiOiJodHRwczovL3N3N3VwLmNibnUuYWMua3IiLCJpc3MiOiLstqnrtoHrjIDtlZnqtZAgU1fspJHsi6zrjIDtlZnsgqzsl4Xri6giLCJzdWIiOiJrbWFobkBjYm51LmFjLmtyIn0.fvE3LYUK6a-VtPcEmlDrOhpHJEMHsAjLSjTUii0BT7jM0hVwEMZTmOCGLpcBsSqzCdJ_fho8wRXYjrMcHOnOeQ

###
# 운영자 로그인
POST http://localhost:3000/operator/login
Content-Type: application/json

{
  "no": "admin",
  "password": "asdf1234"
}

###
# 운영자로 비리 정보 가져오기
GET http://localhost:3001/v1/corruption-report
x-Access-Token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDUxNjBmNTI2OTU2NDVhNjAwNGVmYmUiLCJyb2xlcyI6WyJhZG1pbiJdLCJwZXJtaXNzaW9ucyI6WyJhbGwiXSwiaW5mbyI6IjYwNTE2MGY1MjY5NTY0NWE2MDA0ZWZiZiIsImlhdCI6MTYxNTk2NTYzMywiZXhwIjoxNjE1OTY2MjMzLCJhdWQiOiJodHRwczovL3N3N3VwLmNibnUuYWMua3IiLCJpc3MiOiLstqnrtoHrjIDtlZnqtZAgU1fspJHsi6zrjIDtlZnsgqzsl4Xri6giLCJzdWIiOiJrbWFobkBjYm51LmFjLmtyIn0.BCaAW9Rtsl020m6scJ4-ztO9AeJZmvEnr5pDeYeGvIj7t-mEmhTpSRaQhd48pS8aXwbY2O974q2NZzPIdF4snQ

###
# 특정 비리 정보 가져오기(운영자)
GET http://localhost:3001/v1/corruption-report/6051ac7bb15c664af08c9085
x-Access-Token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDUxNjBmNTI2OTU2NDVhNjAwNGVmYmUiLCJyb2xlcyI6WyJhZG1pbiJdLCJwZXJtaXNzaW9ucyI6WyJhbGwiXSwiaW5mbyI6IjYwNTE2MGY1MjY5NTY0NWE2MDA0ZWZiZiIsImlhdCI6MTYxNTk2NTYzMywiZXhwIjoxNjE1OTY2MjMzLCJhdWQiOiJodHRwczovL3N3N3VwLmNibnUuYWMua3IiLCJpc3MiOiLstqnrtoHrjIDtlZnqtZAgU1fspJHsi6zrjIDtlZnsgqzsl4Xri6giLCJzdWIiOiJrbWFobkBjYm51LmFjLmtyIn0.BCaAW9Rtsl020m6scJ4-ztO9AeJZmvEnr5pDeYeGvIj7t-mEmhTpSRaQhd48pS8aXwbY2O974q2NZzPIdF4snQ

###
# 본인의 특정 비리 정보 가져오기
GET http://localhost:3001/v1/corruption-report/6051ac7bb15c664af08c9085
x-Access-Token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDUxNjM0MTI2OTU2NDVhNjAwNGVmYzAiLCJyb2xlcyI6WyJzdHVkZW50Il0sInBlcm1pc3Npb25zIjpbXSwiaW5mbyI6IjYwNTE2MzQxMjY5NTY0NWE2MDA0ZWZjMSIsImlhdCI6MTYxNTk2NTc0MSwiZXhwIjoxNjE1OTY2MzQxLCJhdWQiOiJodHRwczovL3N3N3VwLmNibnUuYWMua3IiLCJpc3MiOiLstqnrtoHrjIDtlZnqtZAgU1fspJHsi6zrjIDtlZnsgqzsl4Xri6giLCJzdWIiOiJrbWFobkBjYm51LmFjLmtyIn0.NhvXn4zrKIrdFCe-YSr4EcsF7iMMv8F_9RCmmZwD2An3MdtxHye0iJ_cb9rtFGf4jxQljyRFRAdr5wjLg5yGXQ

###
# 다른 사람의 특정 비리 정보 가져오기
GET http://localhost:3001/v1/corruption-report/6051ac7bb15c664af08c9085
x-Access-Token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDUxNjk1YzIxYWVlODM3OTQ5OGMxYzUiLCJyb2xlcyI6WyJzdHVkZW50Il0sInBlcm1pc3Npb25zIjpbXSwiaW5mbyI6IjYwNTE2OTVkMjFhZWU4Mzc5NDk4YzFjNiIsImlhdCI6MTYxNTk2NTc4NywiZXhwIjoxNjE1OTY2Mzg3LCJhdWQiOiJodHRwczovL3N3N3VwLmNibnUuYWMua3IiLCJpc3MiOiLstqnrtoHrjIDtlZnqtZAgU1fspJHsi6zrjIDtlZnsgqzsl4Xri6giLCJzdWIiOiJrbWFobkBjYm51LmFjLmtyIn0.A_JqnrZ2OtQTqHTytPWRE5LbBnktHaa9X1YSTGxySe7S7EXU8pJdfv6_CSOyFsVisXaqeopXPJVsSIFiC3og9w

###
# 운영자가 특정 비리 정보에 댓글 달기
POST http://localhost:3001/v1/corruption-report/6051ac7bb15c664af08c9085/reply
x-Access-Token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDUxNjBmNTI2OTU2NDVhNjAwNGVmYmUiLCJyb2xlcyI6WyJhZG1pbiJdLCJwZXJtaXNzaW9ucyI6WyJhbGwiXSwiaW5mbyI6IjYwNTE2MGY1MjY5NTY0NWE2MDA0ZWZiZiIsImlhdCI6MTYxNTk2NTYzMywiZXhwIjoxNjE1OTY2MjMzLCJhdWQiOiJodHRwczovL3N3N3VwLmNibnUuYWMua3IiLCJpc3MiOiLstqnrtoHrjIDtlZnqtZAgU1fspJHsi6zrjIDtlZnsgqzsl4Xri6giLCJzdWIiOiJrbWFobkBjYm51LmFjLmtyIn0.BCaAW9Rtsl020m6scJ4-ztO9AeJZmvEnr5pDeYeGvIj7t-mEmhTpSRaQhd48pS8aXwbY2O974q2NZzPIdF4snQ
Content-Type: application/json

{
  "content": "댓글 테스트"
}

###
# 댓글 확인(운영자)
GET http://localhost:3001/v1/corruption-report/6051ac7bb15c664af08c9085
x-Access-Token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDUxNjBmNTI2OTU2NDVhNjAwNGVmYmUiLCJyb2xlcyI6WyJhZG1pbiJdLCJwZXJtaXNzaW9ucyI6WyJhbGwiXSwiaW5mbyI6IjYwNTE2MGY1MjY5NTY0NWE2MDA0ZWZiZiIsImlhdCI6MTYxNTk2NTYzMywiZXhwIjoxNjE1OTY2MjMzLCJhdWQiOiJodHRwczovL3N3N3VwLmNibnUuYWMua3IiLCJpc3MiOiLstqnrtoHrjIDtlZnqtZAgU1fspJHsi6zrjIDtlZnsgqzsl4Xri6giLCJzdWIiOiJrbWFobkBjYm51LmFjLmtyIn0.BCaAW9Rtsl020m6scJ4-ztO9AeJZmvEnr5pDeYeGvIj7t-mEmhTpSRaQhd48pS8aXwbY2O974q2NZzPIdF4snQ


###
# 다른 사람이 특정 비리 정보에 댓글 달기
POST http://localhost:3001/v1/corruption-report/6051ac7bb15c664af08c9085/reply
x-Access-Token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDUxNjk1YzIxYWVlODM3OTQ5OGMxYzUiLCJyb2xlcyI6WyJzdHVkZW50Il0sInBlcm1pc3Npb25zIjpbXSwiaW5mbyI6IjYwNTE2OTVkMjFhZWU4Mzc5NDk4YzFjNiIsImlhdCI6MTYxNTk2NTk1OCwiZXhwIjoxNjE1OTY2NTU4LCJhdWQiOiJodHRwczovL3N3N3VwLmNibnUuYWMua3IiLCJpc3MiOiLstqnrtoHrjIDtlZnqtZAgU1fspJHsi6zrjIDtlZnsgqzsl4Xri6giLCJzdWIiOiJrbWFobkBjYm51LmFjLmtyIn0.lsN9HKJhhfq5dniYX3NkZBFSIUWrK3FhKopT1YdIoO7FsZltjUZ3f2qfM8sYekVuz5DsTeF4zIOHIFXd82wKEg
Content-Type: application/json

{
  "content": "다른 사람의 댓글"
}

###
# 본인의 특정 비리 정보에 댓글 달기
POST http://localhost:3001/v1/corruption-report/6051ac7bb15c664af08c9085/reply
x-Access-Token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDNlY2U4ZTI2ODhmNjM4Y2M4NTEzOTYiLCJyb2xlcyI6WyJzdHVkZW50Il0sInBlcm1pc3Npb25zIjpbXSwiaW5mbyI6IjYwM2VjZThlMjY4OGY2MzhjYzg1MTM5NyIsImlhdCI6MTYxNDc0MzIzMCwiZXhwIjoxNjE0NzQzODMwLCJhdWQiOiJodHRwczovL3N3N3VwLmNibnUuYWMua3IiLCJpc3MiOiLstqnrtoHrjIDtlZnqtZAgU1fspJHsi6zrjIDtlZnsgqzsl4Xri6giLCJzdWIiOiJrbWFobkBjYm51LmFjLmtyIn0.BqLQXFPutuGLhfbKtIFbMQaMq-jFx-2O5vhb6z-1jDGZYJauMJMc0V73FNLQDjv1Zm5AZ_qf9HUsnQcFg3_tkg
Content-Type: application/json

{
  "content": "내글에 댓글 달기"
}

###
# 댓글 확인(본인 글)
GET http://localhost:3001/v1/corruption-report/603edcd0a14dc75b9c6f8a7b
x-Access-Token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDNlY2U4ZTI2ODhmNjM4Y2M4NTEzOTYiLCJyb2xlcyI6WyJzdHVkZW50Il0sInBlcm1pc3Npb25zIjpbXSwiaW5mbyI6IjYwM2VjZThlMjY4OGY2MzhjYzg1MTM5NyIsImlhdCI6MTYxNDc0MzIzMCwiZXhwIjoxNjE0NzQzODMwLCJhdWQiOiJodHRwczovL3N3N3VwLmNibnUuYWMua3IiLCJpc3MiOiLstqnrtoHrjIDtlZnqtZAgU1fspJHsi6zrjIDtlZnsgqzsl4Xri6giLCJzdWIiOiJrbWFobkBjYm51LmFjLmtyIn0.BqLQXFPutuGLhfbKtIFbMQaMq-jFx-2O5vhb6z-1jDGZYJauMJMc0V73FNLQDjv1Zm5AZ_qf9HUsnQcFg3_tkg

###
# 대댓글 달기(본인 글)
POST http://localhost:3001/v1/corruption-report/603edcd0a14dc75b9c6f8a7b/reply/603f06062fcd045704d4223c
x-Access-Token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDNlY2U4ZTI2ODhmNjM4Y2M4NTEzOTYiLCJyb2xlcyI6WyJzdHVkZW50Il0sInBlcm1pc3Npb25zIjpbXSwiaW5mbyI6IjYwM2VjZThlMjY4OGY2MzhjYzg1MTM5NyIsImlhdCI6MTYxNDc0MzIzMCwiZXhwIjoxNjE0NzQzODMwLCJhdWQiOiJodHRwczovL3N3N3VwLmNibnUuYWMua3IiLCJpc3MiOiLstqnrtoHrjIDtlZnqtZAgU1fspJHsi6zrjIDtlZnsgqzsl4Xri6giLCJzdWIiOiJrbWFobkBjYm51LmFjLmtyIn0.BqLQXFPutuGLhfbKtIFbMQaMq-jFx-2O5vhb6z-1jDGZYJauMJMc0V73FNLQDjv1Zm5AZ_qf9HUsnQcFg3_tkg
Content-Type: application/json

{
  "content": "대댓글 테스트"
}

###
# 댓글 확인(본인 글)
GET http://localhost:3001/v1/corruption-report/603edcd0a14dc75b9c6f8a7b
x-Access-Token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDNlY2U4ZTI2ODhmNjM4Y2M4NTEzOTYiLCJyb2xlcyI6WyJzdHVkZW50Il0sInBlcm1pc3Npb25zIjpbXSwiaW5mbyI6IjYwM2VjZThlMjY4OGY2MzhjYzg1MTM5NyIsImlhdCI6MTYxNDc0MzIzMCwiZXhwIjoxNjE0NzQzODMwLCJhdWQiOiJodHRwczovL3N3N3VwLmNibnUuYWMua3IiLCJpc3MiOiLstqnrtoHrjIDtlZnqtZAgU1fspJHsi6zrjIDtlZnsgqzsl4Xri6giLCJzdWIiOiJrbWFobkBjYm51LmFjLmtyIn0.BqLQXFPutuGLhfbKtIFbMQaMq-jFx-2O5vhb6z-1jDGZYJauMJMc0V73FNLQDjv1Zm5AZ_qf9HUsnQcFg3_tkg


###
# 대댓글 달기(운영자)
POST http://localhost:3001/v1/corruption-report/603edcd0a14dc75b9c6f8a7b/reply/603f06062fcd045704d4223c
x-Access-Token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDNlZGEzODUyNTBlMzA0OWNmN2UyYzIiLCJyb2xlcyI6WyJhZG1pbiJdLCJwZXJtaXNzaW9ucyI6WyJhbGwiXSwiaW5mbyI6IjYwM2VkYTM4NTI1MGUzMDQ5Y2Y3ZTJjMyIsImlhdCI6MTYxNDc0MzQyOCwiZXhwIjoxNjE0NzQ0MDI4LCJhdWQiOiJodHRwczovL3N3N3VwLmNibnUuYWMua3IiLCJpc3MiOiLstqnrtoHrjIDtlZnqtZAgU1fspJHsi6zrjIDtlZnsgqzsl4Xri6giLCJzdWIiOiJrbWFobkBjYm51LmFjLmtyIn0.XlIhoEsA8UnBc75SgOQExQT9XpzPUVRY4YFajVUxYyV0jtvO_uIX6gnbAHe8ikaCPE2Usl0HZ-bcxhVe5b_t9g
Content-Type: application/json

{
  "content": "운영자 대댓글 테스트"
}

###
# 댓글 확인(본인 글)
GET http://localhost:3001/v1/corruption-report/603edcd0a14dc75b9c6f8a7b
x-Access-Token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDNlY2U4ZTI2ODhmNjM4Y2M4NTEzOTYiLCJyb2xlcyI6WyJzdHVkZW50Il0sInBlcm1pc3Npb25zIjpbXSwiaW5mbyI6IjYwM2VjZThlMjY4OGY2MzhjYzg1MTM5NyIsImlhdCI6MTYxNDc0MzIzMCwiZXhwIjoxNjE0NzQzODMwLCJhdWQiOiJodHRwczovL3N3N3VwLmNibnUuYWMua3IiLCJpc3MiOiLstqnrtoHrjIDtlZnqtZAgU1fspJHsi6zrjIDtlZnsgqzsl4Xri6giLCJzdWIiOiJrbWFobkBjYm51LmFjLmtyIn0.BqLQXFPutuGLhfbKtIFbMQaMq-jFx-2O5vhb6z-1jDGZYJauMJMc0V73FNLQDjv1Zm5AZ_qf9HUsnQcFg3_tkg

###
# 댓글 확인(본인 글)
GET http://localhost:3001/v1/corruption-report/603edcd0a14dc75b9c6f8a7b
x-Access-Token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDNlY2U4ZTI2ODhmNjM4Y2M4NTEzOTYiLCJyb2xlcyI6WyJzdHVkZW50Il0sInBlcm1pc3Npb25zIjpbXSwiaW5mbyI6IjYwM2VjZThlMjY4OGY2MzhjYzg1MTM5NyIsImlhdCI6MTYxNDc0MzIzMCwiZXhwIjoxNjE0NzQzODMwLCJhdWQiOiJodHRwczovL3N3N3VwLmNibnUuYWMua3IiLCJpc3MiOiLstqnrtoHrjIDtlZnqtZAgU1fspJHsi6zrjIDtlZnsgqzsl4Xri6giLCJzdWIiOiJrbWFobkBjYm51LmFjLmtyIn0.BqLQXFPutuGLhfbKtIFbMQaMq-jFx-2O5vhb6z-1jDGZYJauMJMc0V73FNLQDjv1Zm5AZ_qf9HUsnQcFg3_tkg

###
# 비리 정보 수정(본인 글)
PUT http://localhost:3001/v1/corruption-report/603edcd0a14dc75b9c6f8a7b
x-Access-Token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDNlY2U4ZTI2ODhmNjM4Y2M4NTEzOTYiLCJyb2xlcyI6WyJzdHVkZW50Il0sInBlcm1pc3Npb25zIjpbXSwiaW5mbyI6IjYwM2VjZThlMjY4OGY2MzhjYzg1MTM5NyIsImlhdCI6MTYxNDc0MzIzMCwiZXhwIjoxNjE0NzQzODMwLCJhdWQiOiJodHRwczovL3N3N3VwLmNibnUuYWMua3IiLCJpc3MiOiLstqnrtoHrjIDtlZnqtZAgU1fspJHsi6zrjIDtlZnsgqzsl4Xri6giLCJzdWIiOiJrbWFobkBjYm51LmFjLmtyIn0.BqLQXFPutuGLhfbKtIFbMQaMq-jFx-2O5vhb6z-1jDGZYJauMJMc0V73FNLQDjv1Zm5AZ_qf9HUsnQcFg3_tkg
Content-Type: application/json

{
  "title": "수정 테스트",
  "content": "<h1>수정된 글 테스트</h1>"
}

###
# 수정 내용 확인(본인 글)
GET http://localhost:3001/v1/corruption-report/603edcd0a14dc75b9c6f8a7b
x-Access-Token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDNlY2U4ZTI2ODhmNjM4Y2M4NTEzOTYiLCJyb2xlcyI6WyJzdHVkZW50Il0sInBlcm1pc3Npb25zIjpbXSwiaW5mbyI6IjYwM2VjZThlMjY4OGY2MzhjYzg1MTM5NyIsImlhdCI6MTYxNDc0MzIzMCwiZXhwIjoxNjE0NzQzODMwLCJhdWQiOiJodHRwczovL3N3N3VwLmNibnUuYWMua3IiLCJpc3MiOiLstqnrtoHrjIDtlZnqtZAgU1fspJHsi6zrjIDtlZnsgqzsl4Xri6giLCJzdWIiOiJrbWFobkBjYm51LmFjLmtyIn0.BqLQXFPutuGLhfbKtIFbMQaMq-jFx-2O5vhb6z-1jDGZYJauMJMc0V73FNLQDjv1Zm5AZ_qf9HUsnQcFg3_tkg

###
# 비리 정보 수정(운영자)
PUT http://localhost:3001/v1/corruption-report/603edcd0a14dc75b9c6f8a7b
x-Access-Token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDNlZGEzODUyNTBlMzA0OWNmN2UyYzIiLCJyb2xlcyI6WyJhZG1pbiJdLCJwZXJtaXNzaW9ucyI6WyJhbGwiXSwiaW5mbyI6IjYwM2VkYTM4NTI1MGUzMDQ5Y2Y3ZTJjMyIsImlhdCI6MTYxNDc0MzcxOCwiZXhwIjoxNjE0NzQ0MzE4LCJhdWQiOiJodHRwczovL3N3N3VwLmNibnUuYWMua3IiLCJpc3MiOiLstqnrtoHrjIDtlZnqtZAgU1fspJHsi6zrjIDtlZnsgqzsl4Xri6giLCJzdWIiOiJrbWFobkBjYm51LmFjLmtyIn0.P7_5tpn2Oa7oO4BnA0YP7T8NT8MXWyFrnJ_lnPsK2OpWZBFdA-Qtgv2EjEytMlrnjihQVc8Msa67LFXC_dnOcA
Content-Type: application/json

{
  "title": "운영자 수정 테스트",
  "content": "<h1>운영자가 수정된 글 테스트</h1>"
}

###
# 비리글 삭제(다른 사람)
DELETE http://localhost:3001/v1/corruption-report/603edcd0a14dc75b9c6f8a7b
x-Access-Token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDNlY2U2ODYwY2JlODM4MGM3NGMzMWEiLCJyb2xlcyI6WyJzdHVkZW50Il0sInBlcm1pc3Npb25zIjpbXSwiaW5mbyI6IjYwM2VjZTY4NjBjYmU4MzgwYzc0YzMxYiIsImlhdCI6MTYxNDc0Mzc5MSwiZXhwIjoxNjE0NzQ0MzkxLCJhdWQiOiJodHRwczovL3N3N3VwLmNibnUuYWMua3IiLCJpc3MiOiLstqnrtoHrjIDtlZnqtZAgU1fspJHsi6zrjIDtlZnsgqzsl4Xri6giLCJzdWIiOiJrbWFobkBjYm51LmFjLmtyIn0.Fw1u5QL1T0FjbCRIVFZ5dWZ2hVowTGl0XdY7Rq99UJNAxKAJNEgp4E4DDN6mS71wIXIByJCXyDIFQFSdRt-G1A

###
# 비리글 삭제(운영자)
DELETE http://localhost:3001/v1/corruption-report/603edcd0a14dc75b9c6f8a7b
x-Access-Token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDNlZGEzODUyNTBlMzA0OWNmN2UyYzIiLCJyb2xlcyI6WyJhZG1pbiJdLCJwZXJtaXNzaW9ucyI6WyJhbGwiXSwiaW5mbyI6IjYwM2VkYTM4NTI1MGUzMDQ5Y2Y3ZTJjMyIsImlhdCI6MTYxNDc0MzcxOCwiZXhwIjoxNjE0NzQ0MzE4LCJhdWQiOiJodHRwczovL3N3N3VwLmNibnUuYWMua3IiLCJpc3MiOiLstqnrtoHrjIDtlZnqtZAgU1fspJHsi6zrjIDtlZnsgqzsl4Xri6giLCJzdWIiOiJrbWFobkBjYm51LmFjLmtyIn0.P7_5tpn2Oa7oO4BnA0YP7T8NT8MXWyFrnJ_lnPsK2OpWZBFdA-Qtgv2EjEytMlrnjihQVc8Msa67LFXC_dnOcA
